/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package edu.berkeley.gamesman.avro;

@SuppressWarnings("all")
public interface Simple {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Simple\",\"namespace\":\"edu.berkeley.gamesman.avro\",\"types\":[{\"type\":\"record\",\"name\":\"TestRecord\",\"fields\":[{\"name\":\"key\",\"type\":{\"type\":\"string\",\"order\":\"ignore\"}},{\"name\":\"value\",\"type\":\"string\"}]}],\"messages\":{}}");
}
